# Generated by Django 5.1.1 on 2024-12-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='appUser',
        ),
        migrations.AddField(
            model_name='appuser',
            name='hobbies',
            field=models.ManyToManyField(through='api.AppUserHobby', to='api.hobby'),
        ),
    ]
